# Generated by Django 3.0.4 on 2020-06-13 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название жанра')),
            ],
            options={
                'verbose_name_plural': 'Жанр',
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(db_index=True, max_length=15, verbose_name='Оценка')),
            ],
            options={
                'verbose_name_plural': 'Рейтинг',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, verbose_name='Название книги')),
                ('author', models.CharField(db_index=True, max_length=50, verbose_name='Автор')),
                ('dateline', models.CharField(max_length=100, verbose_name='Издательство и год выпуска')),
                ('addition', models.TextField(max_length=1000, verbose_name='Описание')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('time_added', models.DateTimeField(default=datetime.datetime.now)),
                ('genre', models.ManyToManyField(blank=True, related_name='book', to='app.Genre', verbose_name='Раздел')),
                ('rating', models.ManyToManyField(blank=True, related_name='book', to='app.Rating', verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Библиотека',
                'verbose_name_plural': 'Библиотека',
                'ordering': ['-time_added'],
            },
        ),
    ]
