# Generated by Django 3.0.4 on 2020-05-14 13:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200411_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='addition',
            field=models.TextField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 14, 13, 52, 8, 110519)),
        ),
    ]
