# Generated by Django 3.0.4 on 2020-05-15 12:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200514_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 15, 12, 32, 7, 764370)),
        ),
    ]
