# Generated by Django 3.0.4 on 2020-05-15 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200515_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='time_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
